[package]
name = "damccull-cch"
version = "0.1.0"
edition = "2021"
#default-run = "cch"

[lib]
name = "cch"
path = "src/lib.rs"

[[bin]]
name = "damccull-cch"
path = "src/main.rs"

[dependencies]
actix-web = "4.3.1"
shuttle-actix-web = "0.34.0"
shuttle-runtime = { version="0.34.0", default-features = false }
tokio = "1.26.0"
tracing = { version = "0.1.40", features = ["log"] }
tracing-bunyan-formatter = "0.3.9"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
